### ISSUE TITLE
Datavolume CR is disappeared.

### ISSUE THREAD

**Issue by qkfrksvl** [kubevirt-manager/kubevirt-manager#26]
Hi, Thanks for your awesome GUI tool :) 
I've been looking for GUI tool with non integration with openShift. 

One small thing is that DataVolume resource doesn't exist anymore. 
It's just used to make PVC resource and after done making PVC, DataVolume resource is disappeared. 

So, there is no any DataVolume resource in kubevirt-manager. 

Please help :)

**Comment by feitnomore** [comment]
Not sure if the DataVolume in question was created by GUI tool or not, but in the tool, DataVolumes are annotated with `cdi.kubevirt.io/storage.deleteAfterCompletion: "false"` which prevents DataVolume from being deleted after PVC creation is complete. Details here: https://github.com/kubevirt/containerized-data-importer/blob/main/doc/datavolumes.md

**Comment by feitnomore** [comment]
It was an option to `keep` DataVolumes that are related to Kubevirt, so we avoid PVCs that are not related with Kubevirt around GUI tool. This would avoid any confusions.
