### ISSUE TITLE
readwritemany as default option for pvc

### ISSUE THREAD

**Issue by hijak** [kubevirt-manager/kubevirt-manager#28]
hi

great tool! my one problem is

my vm pool wont spin up due to the pvc's being readwriteonce. can we have an option to change this when creating a vmpool or set it as default to readwritemany?

**Comment by feitnomore** [comment]
I'll add this to my backlog, to add the option... I've started as ReadWriteOnce because I was using only hostpath. I already support different StorageClasses(at my lab iSCSI and NFS), however I haven't tried it. I'll add it for sure, stay tuned!
Thanks for the feedback!

**Comment by feitnomore** [comment]
@hijak , I've just merged Rel 1.2.1. If you could take a look at the yamls  and upgrade your installation, I would love to hear some feedback on testing the functionality you've asked for.
Thanks!

**Comment by hijak** [comment]
seems to be two options for type import pvc but other than that its a nice enhancement

**Comment by feitnomore** [comment]
Ok, I'm on vacation so I am not really on top of it, but thanks for the
feedback.

Em ter., 11 de abr. de 2023 06:42, Jack ***@***.***> escreveu:

**Comment by feitnomore** [comment]
@hijak you are right! I've already removed it here on my local copy, but I think I'll wait for more changes before releasing it. Will let you know when I push the code.
Thanks again for using the tool and providing feedback.
