### ISSUE TITLE
custom machine types

### ISSUE THREAD

**Issue by hijak** [kubevirt-manager/kubevirt-manager#29]
ive added some machine types from https://github.com/kubevirt/common-instancetypes/blob/main/common-instancetypes-bundle.yaml and i dont see them when selecting machine type in creation.

**Comment by feitnomore** [comment]
Those are `VirtualMachineInstaceType`, which are namespaced, and would introduce lots of complexity to handle.
`kubevirt-manager` uses `VirtualMachineClusterInstanceType`, which are cluster-wide, as shown on the pic below:

![image](https://user-images.githubusercontent.com/41125128/228510877-697f9d7f-fef4-4270-9d34-7535a700d999.png)

**Comment by feitnomore** [comment]
I would look into this as an example: https://github.com/kubevirt/kubevirt/blob/main/examples/cluster-csmall.yaml

**Comment by feitnomore** [comment]
https://github.com/kubevirt/common-instancetypes/blob/main/common-clusterinstancetypes-bundle.yaml
