### ISSUE TITLE
 That is, when I created the VM, the following error occurred

### ISSUE THREAD

**Issue by 1569099266** [kubevirt-manager/kubevirt-manager#30]
![22e8a3d1c7d1e4af6eefae0731a0350](https://user-images.githubusercontent.com/46311200/230721959-b8c935d4-5159-4a44-a866-08359dbe0262.png)

**Comment by feitnomore** [comment]
Would you be willing to provide more details for me?
First, if possible, I've just released a new version 1.2.1, if you could upgrade it it would really help.
Secondly, if you could open you Developer Tools in you browser, and check for Output Console, and Networking Tab, there should be detailed information. On Network Tab you may see a failed network call that is throwing this error. If you can find it I would be able to see what is going on. Also, if you could provide the request yaml on the failed call it would help me troubleshoot.

Thanks!

**Comment by 1569099266** [comment]
Can you guys do a remote support to see why

**Comment by 1569099266** [comment]
![image](https://user-images.githubusercontent.com/46311200/230750459-16707f01-2f64-492e-becc-36db4ba413ba.png)
![image](https://user-images.githubusercontent.com/46311200/230750484-6c1679e3-38c7-4fdb-b9ae-318fc86c167e.png)
The approximate reason is as follows

**Comment by feitnomore** [comment]
The second error message is pretty clear. CDI is lacking on your cluster.
Documentation is clear on the CDI requirement:
![image](https://user-images.githubusercontent.com/41125128/230771672-32bb8516-0792-44ea-a43d-a16b0aa078c9.png)

Would you please try to install CDI? Remember to config the needed featuregates and storageclasses.
https://github.com/kubevirt/containerized-data-importer
Thanks!
