### ISSUE TITLE
Is there a small problem with this Nginx? I will not report an error when I visit /vmpool, but I will throw a 404 error when I refresh it. Then my VM still can’t get up. I deployed a CDI, and then I can’t get up. Less than detailed logs, and can you add authentication

### ISSUE THREAD

**Issue by 1569099266** [kubevirt-manager/kubevirt-manager#32]
![image](https://user-images.githubusercontent.com/46311200/230778493-c40ec9d7-1454-489d-838a-3037b4fa47f5.png)
![image](https://user-images.githubusercontent.com/46311200/230778524-bc70332a-6550-4414-9f8d-03e576219ecc.png)
![image](https://user-images.githubusercontent.com/46311200/230778578-62ecf05a-8523-4353-9342-ac7fa6b3ef48.png)

**Comment by feitnomore** [comment]
Unfortunately the tool does not understand paths directly put into the URL
bar because of routing complexity, so you should visit / and go from there.

Em dom., 9 de abr. de 2023 10:32, 1569099266 ***@***.***>
escreveu:

**Comment by feitnomore** [comment]
Also for the VM not getting UP, CDI takes sometime tô import images. I
would sugest checking the volumes window, otherwise probably you will need
to use kubectl tô check what os going on.

Em dom., 9 de abr. de 2023 11:38, Marcelo Feitoza Parisi <
***@***.***> escreveu:
