### ISSUE TITLE
 Can you add expose VM virtual machine through NodePort?

### ISSUE THREAD

**Issue by 1569099266** [kubevirt-manager/kubevirt-manager#34]
Can you add web authentication function and expose VM virtual machine through NodePort?

**Comment by feitnomore** [comment]
ok, please, first lets split this in 2 different things.... 
I've renamed this one to NodePort, as this is the straightforward one.
Could you please get a new one for Auth?? Also, is just a plain user/pass (nginx auth) enought or are you talking about roles/groups and advanced access control?
Thanks!

**Comment by 1569099266** [comment]
Using nginx authentication is sufficient, don't need user groups, use rabc authentication



发自我的iPhone


------------------ Original ------------------
From: Marcelo Feitoza Parisi ***@***.***&gt;
Date: Sun,Apr 16,2023 9:50 PM
To: kubevirt-manager/kubevirt-manager ***@***.***&gt;
Cc: 1569099266 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [kubevirt-manager/kubevirt-manager]  Can you add expose VMvirtual machine through NodePort? (Issue #34)





 
ok, please, first lets split this in 2 different things....
 I've renamed this one to NodePort, as this is the straightforward one.
 Could you please get a new one for Auth?? Also, is just a plain user/pass (nginx auth) enought or are you talking about roles/groups and advanced access control?
 Thanks!

**Comment by 1569099266** [comment]
Can you write an operater to install the required components of kubevirt with one click



发自我的iPhone


------------------ Original ------------------
From: Marcelo Feitoza Parisi ***@***.***&gt;
Date: Sun,Apr 16,2023 9:50 PM
To: kubevirt-manager/kubevirt-manager ***@***.***&gt;
Cc: 1569099266 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [kubevirt-manager/kubevirt-manager]  Can you add expose VMvirtual machine through NodePort? (Issue #34)





 
ok, please, first lets split this in 2 different things....
 I've renamed this one to NodePort, as this is the straightforward one.
 Could you please get a new one for Auth?? Also, is just a plain user/pass (nginx auth) enought or are you talking about roles/groups and advanced access control?
 Thanks!

**Comment by feitnomore** [comment]
I think an operator to install everything with a single click is way out of the scope of this tool for now. Unfortunately I'm working on best effort here, and I have a huge backlog of functionalities to implement before that.

**Comment by 1569099266** [comment]
Thank you very much. Thank you very much



发自我的iPhone


------------------ Original ------------------
From: Marcelo Feitoza Parisi ***@***.***&gt;
Date: Sun,Apr 16,2023 10:10 PM
To: kubevirt-manager/kubevirt-manager ***@***.***&gt;
Cc: 1569099266 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [kubevirt-manager/kubevirt-manager]  Can you add expose VMvirtual machine through NodePort? (Issue #34)





 
I think an operator to install everything with a single click is way out of the scope of this tool for now. Unfortunately I'm working on best effort here, and I have a huge backlog of functionalities to implement before that.

**Comment by feitnomore** [comment]
The `NodePort` feature is already implemented. I am going to test it over the week, together with some new changes, and probably release by next week. Thanks!
