### ISSUE TITLE
more options for network

### ISSUE THREAD

**Issue by hijak** [kubevirt-manager/kubevirt-manager#35]
the ability to choose the bridge option or others would be a nice addition 

https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/#frontend

for example i want podnetworking in bridge mode

**Comment by feitnomore** [comment]
So, `bridge`, `slirp` and `masquerade`(in this without specifying ports, in other works, masquerading everything) should be pretty straightforward. The other options looks like a little bit more complex and I don't really have an environment to test those options. What are your thoughts?

**Comment by feitnomore** [comment]
Also, today here is the logic behind it:
```
            /* Networking Setup */
            if(newvmnetwork != "podNetwork") {
                net1 = {'name': "br0", 'multus': {'networkName': newvmnetwork}};
                iface1 = { 'name': "br0", 'bridge': {}};
            } else {
                net1 = {'name': "default", 'pod': {}};
                iface1 = {'name': "default",'masquerade': {}};
            }
  ```

**Comment by hijak** [comment]
well personally i am only interested in selecting the bridge frontend for podnetworking network

eg:

```
spec:
  domain: 
    interfaces:
```

**Comment by feitnomore** [comment]
I'll refactor this piece so that I can add at least those 2 options.

Em seg., 17 de abr. de 2023 04:04, Jack ***@***.***> escreveu:

**Comment by feitnomore** [comment]
Ok, I've done some testing today, and I need to add some more logic, as `masquerade` option is only valid for `podNetwork` according to the error messages I had, so I need to plan something on the UI to make sure the user won't be able to select anything that doesn't work.
