### ISSUE TITLE
After a few minutes the page shows a 404 error

### ISSUE THREAD

**Issue by yule-sun** [kubevirt-manager/kubevirt-manager#40]
After the deployment is complete, the console page of kubevirt-manage can be accessed normally, but after a few minutes, there will be a 404 error and cannot be accessed. I have to close the current page and reopen it.
![image](https://github.com/kubevirt-manager/kubevirt-manager/assets/37107125/2363f252-ff87-4aed-937f-97bb645c1ff5)

![image](https://github.com/kubevirt-manager/kubevirt-manager/assets/37107125/874ff4db-8977-48cf-ab3d-94db898dfa71)

And I found that the virtual machine cannot be created through Virtual Machines, VM Pools is blank. Cannot add anything in Data Volumes and Instance type. Where am I going wrong?

**Comment by feitnomore** [comment]
The 404 is kinda expected as this is a SPA... the only URL that works is the root one.
About the other errors, would you open the browser Developer Tools and take a look into Console and Networking tabs to get some clues on what is going on?
Thanks!

**Comment by feitnomore** [comment]
The 404 error is being handled by #41
