### ISSUE TITLE
Need to support sending Ctrl+Alt+Del and other shortcut keys

### ISSUE THREAD

**Issue by wynterwang** [kubevirt-manager/kubevirt-manager#44]
The current functionality of VNC Viewer is too simple. It needs to at least support sending some common shortcut keys (e.g. Ctrl+Alt+Del) to meet daily work needs, such as accessing Windows servers, without the ability to send Ctrl+Alt+Del, it is impossible to login the system. I sincerely hope that the next version can support sending common shortcut keys. It would be even better if more features such as power on/off and clipboard support can be added in the future.

https://github.com/novnc/noVNC/blob/master/docs/API.md

**Comment by feitnomore** [comment]
Thank you for submitting this and also pointing the documentation.

**Comment by feitnomore** [comment]
@wynterwang , would you try image 1.3.1? Just update your deployment image to 1.3.1.
I've changed it for the noVNC example with toolbar support so that you can use keys and clipboard.
Thanks!

**Comment by wynterwang** [comment]
We have already experienced it in our environment, it’s awesome, thanks a lot!
