### ISSUE TITLE
Can you provide some docker images for centos and ubuntu suitable for running kubevirt?

### ISSUE THREAD

**Issue by 1569099266** [kubevirt-manager/kubevirt-manager#47]
Can you provide some docker images for centos and ubuntu suitable for running kubevirt?

**Comment by feitnomore** [comment]
You mean running Kubevirt inside a Kubernetes Cluster created using Cluster API? Can you please be more specific? Thanks!

**Comment by 1569099266** [comment]
containers:
         - name: demo
           image: centosxxx mirror

**Comment by feitnomore** [comment]
Sorry, I don't understand what you're asking for...
