### ISSUE TITLE
LoadBalancer `Target Resource` options not populated unless other fields toggled first

### ISSUE THREAD

**Issue by cloudymax** [kubevirt-manager/kubevirt-manager#50]
First of all, thanks so much for making this project, it's been a fantastic tool for my home-lab as well as for showing off Kubevirt's features to friends and colleagues! 

The issue I'm seeing is that when creating a LoadBalancer with the goal of attaching it to an existing VM, the `Target Instance` field is unpopulated until another option is toggled (changing the namespace for example). Once the toggle action has been performed though, everything works as expected.

Here is a short video of the issue:

https://github.com/kubevirt-manager/kubevirt-manager/assets/84841307/da098814-db86-4024-96e3-9292880c5026

Cheers!

**Comment by feitnomore** [comment]
First of all, thanks for reporting the issue and using the tool. Feedback is always important for me.
I am thinking about 2 approaches to solve this issue, and leaning on the 1st one as it'll be more easier:
1. Have the namespace selector load empty, so you'll be forced to select one
2. Load the options based on the first namespace of the list that comes selected (which will probably involve an extra API Call that might not be even used)

**Comment by feitnomore** [comment]
I'm submitting the fix right now.
