### ISSUE TITLE
datavolumes are not displayed on /dsklist page

### ISSUE THREAD

**Issue by heimdull** [kubevirt-manager/kubevirt-manager#54]
I can see on the dashboard page that I have 13 datavolumes but there are none displayed when I click the "More Info" button for /dsklist.

cdi v1.58.1
kubevirt v1.2.0-rc1
rke2 v1.27.8

I do have data on vms, nodes, networks as expected. I was able to create a new empty datavolume successfully but this also did not show in the dsklist

I do have ExpandDisks and HonorWaitForFirstConsumer featureGates enabled. My storage classes has the allowVolumeExpansion set to true.

**Comment by heimdull** [comment]
maybe this is a me problem... just installed kubevirt-manager on another rke2 cluster we have and the datavolumes do load in this cluster... looking to see whats different now

**Comment by feitnomore** [comment]
@heimdull , compare the yaml files for the data volumes on both clusters.
On the cluster that is not working, I would suggest opening the Developer Tools on your navigator, and check the Console, as well as the Networking tab.
Thanks!

**Comment by heimdull** [comment]
In the console on the one that is broken I get this 
```
TypeError: Cannot read properties of undefined (reading 'storageClassName')
    at main.0c3b6b4d5d1665c3.js:1:509191
    at Generator.next (<anonymous>)
    at hk (main.0c3b6b4d5d1665c3.js:1:213215)
    at r (main.0c3b6b4d5d1665c3.js:1:213417)
    at v.invoke (polyfills.de4fc2210fb770ce.js:1:6566)
    at Object.onInvoke (main.0c3b6b4d5d1665c3.js:1:91533)
    at v.invoke (polyfills.de4fc2210fb770ce.js:1:6506)
    at M.run (polyfills.de4fc2210fb770ce.js:1:1962)
    at polyfills.de4fc2210fb770ce.js:1:16763
    at v.invokeTask (polyfills.de4fc2210fb770ce.js:1:7184)
```

checking this url I get whats expected... it looks correct https://kubevirt-manager/k8s/apis/cdi.kubevirt.io/v1beta1/datavolumes

**Comment by feitnomore** [comment]
If you compare the result for the URL on one cluster and on the other one, my guess is that one of them is missing the StorageClassName config setting. Can you paste the result?

**Comment by heimdull** [comment]
[working-site.txt](https://github.com/kubevirt-manager/kubevirt-manager/files/14516021/working-site.txt)
[broken-site.txt](https://github.com/kubevirt-manager/kubevirt-manager/files/14516022/broken-site.txt)

**Comment by feitnomore** [comment]
I think I've nailed down the problem, but I will need to *consult* with CDI folks on something, before I can go ahead and propose a fix.

**Comment by feitnomore** [comment]
Your problem seems to be related to the fact that few of your `DataVolumes` have `spec.pvc` while others have `spec.storage`, and this tool is looking for `spec.pvc`. I'm trying to get some answers from the Kubevirt team on what's the difference between them, to have this fixed.

**Comment by feitnomore** [comment]
I don't have the exact setup here, but I'll try to work to get an image for you to test, sounds good?

**Comment by heimdull** [comment]
That works for me, I appreciate the help

**Comment by heimdull** [comment]
running the 1.3.3 image resolves the issue. I can see all the datavolumes now.

**Comment by feitnomore** [comment]
I'm merging the PR now. You'll probably want to update your image once more, as I've figured there were other pieces that needed work as well.

Thanks for opening this issue!
