### ISSUE TITLE
NoVNC Connection Error.

### ISSUE THREAD

**Issue by anfechtung** [kubevirt-manager/kubevirt-manager#59]
I am attempting to access a VM console using kubevirt-manager's NoVNC client.  However I consistently get errors when trying to connect.

![image](https://github.com/kubevirt-manager/kubevirt-manager/assets/140758185/1ab9e4be-f218-4a74-bce0-2e60dbd6edce)

I'm really not sure where to start looking to debug the issue.  Any guidance would be much appreciated.

**Comment by feitnomore** [comment]
Can you share details about your setup? Are you running locally or inside the cluster? are you using ingress? if you try to port-forward to the pod, the error still happening? Does it happen for any VM?

**Comment by feitnomore** [comment]
I am not sure how this would behave behind a virtual service on istio.... would you please try to port-fw to the kubevirt-manager pod? The tricky here is that NoVNC needs Websocket, and depending on how the Ingress is setup, it may not work, so if you can get it working through port-forward, we'll nail down the problem to the istio ingress.

**Comment by anfechtung** [comment]
I believe the url for the websocket connection might be malformed.  The url in the header of the wss request looks something like:
`wss://kubevirt.mydomain.site//k8s/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/fedora-vmi/vnc.`

If I manually create a websocket in the debug console with the same url, I get the same error.  However if I fix the url (remove the extra /), I can create the web socket object.

Failing:
```
// Create WebSocket connection.
const socket = new WebSocket("wss://kubevirt.mydomain.site//k8s/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/fedora-vmi/vnc");

// Connection opened
socket.addEventListener("open", (event) => {
  socket.send("Hello Server!");
});

// Listen for messages
socket.addEventListener("message", (event) => {
  console.log("Message from server ", event.data);
});
---
VM360:2 WebSocket connection to 'wss://kubevirt.mydomain.site//k8s/apis/subresources.k…virt.io/v1alpha3/namespaces/default/virtualmachineinstances/fedora-vmi/vnc' failed: 
```

Working:
```
// Create WebSocket connection.
const socket = new WebSocket("wss://kubevirt.mydomain.site/k8s/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/fedora-vmi/vnc");

// Connection opened
socket.addEventListener("open", (event) => {
  socket.send("Hello Server!");
});

// Listen for messages
socket.addEventListener("message", (event) => {
  console.log("Message from server ", event.data);
});

---
Message from server  Blob {size: 12, type: ''}
```

**Comment by feitnomore** [comment]
This has something to do with the way the ingress is setup... In some setups, looks like it adds the extra / while in others no... I'll see if I can do somthing like a find/replace to fix it.

**Comment by feitnomore** [comment]
I'm on vacation but I'll see if I can do some testing over here. In my environment it works ok, and generally speaking you are the 1st person that complains about it. I've seen these kind of problems before but most of them were related to the fact that I was running the app locally, or some kind of problem in my ingress setup.

**Comment by feitnomore** [comment]
I'm merging a PR to try to fix this issue. Would you please make sure you remove your actual image from local node caches and try to re-download the image and see if it gets better? Anyways, this might be related to the way your ingress works. I hope I don't break this for other people.

**Comment by anfechtung** [comment]
which image should i pull/use?  I currently have `image: kubevirtmanager/kubevirt-manager:1.3.3`

**Comment by feitnomore** [comment]
The same tag please....

Em qua., 3 de abr. de 2024 11:42, anfechtung ***@***.***>
escreveu:
