### ISSUE TITLE
Pre-installation question, requirements

### ISSUE THREAD

**Issue by stianmathisen** [kubevirt-manager/kubevirt-manager#66]
Hello,

I'm just getting started using this lovely tool and was a bit confused. Do I have to deploy kubevirt separatly or does this tool include it? I tried to look all over the github and the website but could not see it mentioned.

**Comment by feitnomore** [comment]
You need to have Kubevirt pre-installed as well as CDI.
1. For kubevirt: https://kubevirt.io/user-guide/cluster_admin/installation/#installing-kubevirt-on-kubernetes
2. For CDI: https://kubevirt.io/user-guide/storage/containerized_data_importer/#install-cdi
3. If you plan to use Cluster API: https://cluster-api.sigs.k8s.io/user/quick-start.html?highlight=kubevirt

Remember, your Kubevirt installation and CDI installation should follow these requirements:
<img width="872" alt="image" src="https://github.com/user-attachments/assets/ce12bb56-1c17-4ba9-84a0-56f9be5b44e6">
