### ISSUE TITLE
about  instance type  create error

### ISSUE THREAD

**Issue by zhujunxing123** [kubevirt-manager/kubevirt-manager#68]
May I consult with experts? When I use the instance type feature of kubevirt manager to create a new cluster instance type, it prompts' undefined '. Then, when I check netwokr in the browser, I find a 404 error. What is the general reason for this error?
The kubevirt version is 0.59 and the manager version is 1.4

**Comment by feitnomore** [comment]
This is probably because the API Version got deprecated on new versions. Can you comment for me the URL that you're getting the 404 error? Thanks!

**Comment by feitnomore** [comment]
I'm updating code to use `v1beta1` as per [kubevirt Issue #12391](https://github.com/kubevirt/kubevirt/issues/12391).

**Comment by feitnomore** [comment]
Closing as per [kubevirt issue #12391](https://github.com/kubevirt/kubevirt/issues/12391)
