### ISSUE TITLE
Ability to add volumes to a running VM

### ISSUE THREAD

**Issue by kleinjoshuaa** [kubevirt-manager/kubevirt-manager#78]
![image](https://github.com/user-attachments/assets/cbe24279-32e0-403c-a7d8-d7f21e170382)

It would be nice to be able to hotplug volumes to a running VM. Currently this feature does not exist in kubevirt-manager

**Comment by feitnomore** [comment]
Hello @kleinjoshuaa .

I'm trying to revisit the DISK implementation on this tool to see if I can accommodate that functionality.
Thanks for the feedback!

**Comment by feitnomore** [comment]
Added Hotplug support on 1.4.1, please validate!
