### ISSUE TITLE
Wrong Memory format when creating new Instance Type

### ISSUE THREAD

**Issue by csman964** [kubevirt-manager/kubevirt-manager#82]
Hello,

When creating a new instance type the memory doesn't have the "Gi" extension, so we cannot use it like this without error. We must modify it, retype the right memory size and validate in order to work.

![Screenshot from 2024-09-04 11-29-23](https://github.com/user-attachments/assets/14d7bef8-3129-4cac-b07e-05499af197e7)

Version : 1.4.0

Thank you

**Comment by feitnomore** [comment]
Can you tell me in which screen you see that? Is it on Instance Types?

**Comment by csman964** [comment]
Yes it's on the "Instance Types" screen.

**Comment by feitnomore** [comment]
Fixed on 1.4.1, please validate!

**Comment by csman964** [comment]
Problem fixed in this version 1.4.1. Thank you. :)
